Adds PR to CI workflow
UC-Davis-molecular-computing/scadnano-python-package pull request #143
Opened 2020-10-02 18:22 UTC by UnHumbleBen

This fixes issue where PR from external forks would not have
CI checks, as in [this PR](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/pull/142).

This commit fixes this issue, as shown in this
[sample PR](https://github.com/UnHumbleBen/scadnano-python-package-1/pull/5).
You can see that CI tests run now.

2020-10-02 18:27 UTC, dave-doty requested changes
Is there any way to do it where it does not run two redundant checks when we do PRs? The one you just created, for instance, has two versions of each check:

![image](https://user-images.githubusercontent.com/19274365/94957103-0fba1b00-04a2-11eb-86da-777be72cf74b.png)

Probably not a huge deal, but I'd like to do this on the Dart repo as well, and that one has much longer-running CI, and I recall an email recently indicating that they are limiting the number of CI minutes we get per month for free.

2020-10-02 18:42 UTC, UnHumbleBen commented
What do you think of removing the `push` event? I.e. CI will only run with when PR is made and updated (i.e. commits made on PR).

2020-10-02 18:44 UTC, dave-doty commented
> What do you think of removing the `push` event? I.e. CI will only run with when PR is made and updated (i.e. commits made on PR).

Sure, if that achieves the desired behavior.

2020-10-02 19:08 UTC, UnHumbleBen commented
This should give us the desired behavior. Since we can't push directly to `dev` anymore, any changes we made to `dev` will be done via PRs, so every change to `dev` will have CI workflow run on it. When `dev` to `master`, CI checks will be done here as well.

2020-10-03 20:38 UTC, dave-doty approved these changes

2020-10-03 21:18 UTC, merged